version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: darth999-aurum-node_aurum-node_1
      APP_PORT: 9888

  aurum-node:
    image: ariworksonline/aurum-node:latest@sha256:51bee14363af3d85c2fd3d31845c44825cebef840884f1c9e7d866f3502ed0c7
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/root/.aurum
    ports:
      - "9889:9889"
