version: "3.7"

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@umbrel.local
      PGADMIN_DEFAULT_PASSWORD: umbrel
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - umbrel_main_network
      - miningcore-pool_default

networks:
  umbrel_main_network:
    external: true
  miningcore-pool_default:
    external: true
