version: "3.7"

services:
  aurum-node:
    image: ariworksonline/aurum-node:latest
    container_name: aurum-node
    restart: unless-stopped
    volumes:
      - aurum-data:/root/.aurum
    ports:
      - "9889:9889"
      - "9888:9888"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9889"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  aurum-data:
